In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical


In [ ]:
np.random.seed(42)

data = {
    'user': ['User1'] * 50 + ['User2'] * 50 + ['User3'] * 50,
    'avg_time': np.random.normal(loc=0.2, scale=0.05, size=150),
    'std_dev_time': np.random.normal(loc=0.02, scale=0.01, size=150),
}


In [ ]:
data = {
  'user' : ['User 1']*50 + ['User 2']*50 + ['User 3'] * 50,
  'avg_time' : np.random.normal(loc=0.2, scale=0.05, size=150),
  'std_dev_time' : np.random.normal(loc=0.02, scale=0.01, size=150)
}

df = pd.DataFrame(data)

X = df[['avg_time', 'std_dev_time']].values
y = df['user'].values



In [ ]:
df = pd.DataFrame(data)


X = df[['avg_time', 'std_dev_time']].values
y = df['user'].values


y = pd.factorize(y)[0]
y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f'X: {X}')
print(f'y :{y}')

X: [[ 0.15855025  0.01937321]
 [ 0.17199095  0.02955142]
 [ 0.23736468  0.01014274]
 [ 0.23051851  0.02504047]
 [ 0.19895492  0.01469742]
 [ 0.20586637  0.01207127]
 [ 0.26388324  0.0189297 ]
 [ 0.17042143  0.00964758]
 [ 0.22735487  0.01446351]
 [ 0.18989037  0.00802122]
 [ 0.18911594  0.03964725]
 [ 0.25493884  0.02035264]
 [ 0.24127082  0.01300274]
 [ 0.24067548  0.0221398 ]
 [ 0.26527394  0.01887672]
 [ 0.20105019  0.0177903 ]
 [ 0.23409765  0.02614167]
 [ 0.18448666  0.02757508]
 [ 0.21620832  0.01469499]
 [ 0.19349285  0.01424182]
 [ 0.2048498   0.01724948]
 [ 0.22975785 -0.00301921]
 [ 0.15908897  0.00484809]
 [ 0.30461936  0.03366874]
 [ 0.14969913  0.03644968]
 [ 0.13929057  0.01750964]
 [ 0.25790554  0.02576557]
 [ 0.23958313  0.0231125 ]
 [ 0.23120599  0.05078881]
 [ 0.23141728  0.03119575]
 [ 0.19938766  0.01872082]
 [ 0.15513728  0.0104446 ]
 [ 0.20379023  0.00393554]
 [ 0.16614191  0.02203464]
 [ 0.24875599  0.01243649]
 [ 0.19264713  0.00577746]
 [ 0.15872514  0.01353427

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(8, activation='relu'))
model.add(Dense(y_train.shape[1], activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
X_train.shape

(120, 2)

In [ ]:
model.compile(optimizer='SGD',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


model.fit(X_train_scaled, y_train, epochs=50, batch_size=5, validation_split=0.2)


Epoch 1/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.4121 - loss: 1.0956 - val_accuracy: 0.1250 - val_loss: 1.2144
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3969 - loss: 1.1194 - val_accuracy: 0.1250 - val_loss: 1.2036
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3269 - loss: 1.0915 - val_accuracy: 0.1667 - val_loss: 1.1851
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3476 - loss: 1.1046 - val_accuracy: 0.1667 - val_loss: 1.1755
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3931 - loss: 1.1053 - val_accuracy: 0.2083 - val_loss: 1.1735
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3506 - loss: 1.1036 - val_accuracy: 0.2083 - val_loss: 1.1662
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3461 - loss: 1.1024 - val_accuracy: 0.1667 - val_loss: 1.1651
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4473 - loss: 1.0854 - val_accuracy: 0.1667 - val_loss

In [ ]:
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2333 - loss: 1.1557
Test Loss: 1.1557, Test Accuracy: 0.2333


In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)


y_pred = model.predict(X_test_scaled)


#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(y_pred)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.33      0.11      0.17         9
           2       0.25      0.09      0.13        11

   micro avg       0.13      0.07      0.09        30
   macro avg       0.19      0.07      0.10        30
weighted avg       0.19      0.07      0.10        30
 samples avg       0.07      0.07      0.07        30

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler


data = {
    'user': ['User1'] * 50 + ['User2'] * 50 + ['User3'] * 50,
    'avg_time': np.random.normal(loc=0.2, scale=0.05, size=150),
    'std_dev_time': np.random.normal(loc=0.02, scale=0.01, size=150),
}

df = pd.DataFrame(data)


X = df[['avg_time', 'std_dev_time']]
y = df['user']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=1500, random_state=143)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(y_pred)


[[8 0 2]
 [4 2 3]
 [4 2 5]]
              precision    recall  f1-score   support

       User1       0.50      0.80      0.62        10
       User2       0.50      0.22      0.31         9
       User3       0.50      0.45      0.48        11

    accuracy                           0.50        30
   macro avg       0.50      0.49      0.47        30
weighted avg       0.50      0.50      0.47        30

['User1' 'User1' 'User1' 'User3' 'User3' 'User1' 'User3' 'User1' 'User1'
 'User2' 'User3' 'User1' 'User3' 'User1' 'User1' 'User1' 'User2' 'User2'
 'User1' 'User1' 'User3' 'User3' 'User1' 'User1' 'User3' 'User3' 'User3'
 'User2' 'User1' 'User1']
